name: Auto-Simulate Daily Crawl

on:
  schedule:
    - cron: '0 8 * * *' # Täglich um 8 Uhr (UTC)
  workflow_dispatch:

jobs:
  crawl-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Daily Crawl
        env:
          FIREBASE_CONFIG_BASE64: ${{ secrets.FIREBASE_CONFIG_BASE64 }} # You have to set this in Github
        run: npx tsx scrape_all.ts

